server:
  port: 28080
spring:
  config:
    import: "optional:consul:"
  cloud:
    consul:
      discovery:
        fail-fast: true
        instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
      host: consul.srivittal.com
      port: 8500
      config:
        enabled: true
        format: yaml
        acl-token: 2bd18067-2fd6-3a43-669b-91d56be83457
  application:
    name: "RestConsumer"
