spring:
  config:
    import: "optional:consul:"
  cloud:
    consul:
      discovery:
        enabled: true
        fail-fast: true
        instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
        service-name: ${spring.application.name}
        register: true
        deregister: true
        acl-token: 6f1243f0-3bb2-6143-e6ba-403e6debd47b
      host: consul.srivittal.com
      port: 8501
      config:
        enabled: true
        format: yaml
        acl-token: "6f1243f0-3bb2-6143-e6ba-403e6debd47b"
      scheme: https
  application:
    name: "RestService"
server:
  port: 28081