spring:
  config:
    import: "consul:"
  cloud:
    consul:
      discovery:
        fail-fast: true
        instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
        service-name: ${spring.application.name}
      host: consul.srivittal.com
      port: 8500
      config:
        enabled: true
        format: yaml
  application:
    name: "RestService"
