name: learn-github-actions
run-name: ${{ github.actor }} is learning GitHub Actions
on: [push, workflow_dispatch]
jobs:
  check-bats-version:
    runs-on: [self-hosted, linux, mac16]
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v3
        with:
          node-version: '14'
      - run: npm install -g bats
      - run: bats -v
      - name: Set up JDK 17 for x64
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          architecture: x64
      - name: Setup Maven Action
        uses: s4u/setup-maven-action@v1.11.0
        with:
          java-version: 17
          maven-version: 3.9.5
      - name: Run the Maven verify phase
        run: mvn --verify